image: buildpack-deps:xenial

before_script:
- apt install -y lua-dev libeigen3-dev

build:
    script: "./make.sh 2>&1 | tee build.log"
    artifacts:
        when: always
        expire_in: 1 week
        paths:
        - build.log
        - build/
